version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 2121:2121 

volumes:
 db:
